name: Docker Image CI
permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
on: 
  push:
  release:
    types: [published]
env:
  IMAGE_NAME: ${{ github.repository }}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: echo Package ${{ github.event.release.tag_name }}
    - name: Login to GHCR
      run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build . \
        --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"
    - name: Push to Docker GHCR
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        PACKAGE_VERSION=$(echo ${{ github.event.release.tag_name }})
        [ -z "$PACKAGE_VERSION" ] && VERSION=latest
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        [ "$VERSION" == "main" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        echo PACKAGE_VERSION=$PACKAGE_VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        [ -z "$PACKAGE_VERSION" ] || docker tag $IMAGE_NAME $IMAGE_ID:$PACKAGE_VERSION
        docker push $IMAGE_ID:$VERSION
        [ -z "$PACKAGE_VERSION" ] || docker push $IMAGE_ID:$PACKAGE_VERSION